name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run Go Linter
    strategy:
      matrix:
        os: ['ubuntu-latest']
        go-version: ['1.20','1.21', '1.22']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  unit-testing:
    name: Run Unit Tests
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        go-version: [ '1.20','1.21', '1.22' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Run Unit Testing
        run: go test ./... -cover -v

  integration-testing:
    name: Run Integration Tests
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        go-version: [ '1.20','1.21', '1.22' ]
    runs-on: ${{ matrix.os }}
    needs: ['unit-testing']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Run Integration Testing
        run: go test ./... -tags=integration -cover